(() => {
'use strict';
const DB_NAME='fittrack-local', STORE='entries', PROFILE='fittrack-v2-profile', FOCUS='fittrack-v2-focus', SEED='fittrack-v2-seed-32-v1';
const TARGETS={protein:140,fiber:30,steps:11500,water:2.5,sleep:8};
let db, entries=[], currentPeriod='month', editingDate=null, pendingAction=null, deferredPrompt=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const n0=new Intl.NumberFormat('de-DE',{maximumFractionDigits:0}), n1=new Intl.NumberFormat('de-DE',{maximumFractionDigits:1});
const dateShort=new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit',year:'numeric'});
const dateLong=new Intl.DateTimeFormat('de-DE',{weekday:'long',day:'2-digit',month:'long',year:'numeric'});
const toDate=s=>new Date(s+'T12:00:00');
const balance=e=>Number(e.intake||0)-Number(e.tdee||0);
const signed=v=>(v>0?'+':v<0?'−':'')+n0.format(Math.abs(v))+' kcal';
const kcal=v=>v==null?'–':n0.format(v)+' kcal';
const fmt=(v,u='',dec=1)=>v==null||v===''?'–':(dec?n1:n0).format(Number(v))+u;
const optional=v=>v===''||v==null?null:Number(v);
const todayIso=()=>{let d=new Date;return new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,10)};
function openDb(){return new Promise((ok,no)=>{let r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:'date'})};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
function store(mode='readonly'){return db.transaction(STORE,mode).objectStore(STORE)}
function getAll(){return new Promise((ok,no)=>{let r=store().getAll();r.onsuccess=()=>ok(r.result||[]);r.onerror=()=>no(r.error)})}
function getOne(k){return new Promise((ok,no)=>{let r=store().get(k);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
function put(e){return new Promise((ok,no)=>{let r=store('readwrite').put(e);r.onsuccess=ok;r.onerror=()=>no(r.error)})}
function remove(k){return new Promise((ok,no)=>{let r=store('readwrite').delete(k);r.onsuccess=ok;r.onerror=()=>no(r.error)})}
function clear(){return new Promise((ok,no)=>{let r=store('readwrite').clear();r.onsuccess=ok;r.onerror=()=>no(r.error)})}
async function seedMissing(){if(localStorage.getItem(SEED))return;const old=await getAll(), dates=new Set(old.map(e=>e.date));for(const raw of window.FITTRACK_SEED_DATA||[]){if(!dates.has(raw.date))await put({...raw,trainingType:raw.trainingType||''})}localStorage.setItem(SEED,'1')}
function profile(){try{return JSON.parse(localStorage.getItem(PROFILE))||{name:'Jenny'}}catch{return{name:'Jenny'}}}
function focus(){try{return JSON.parse(localStorage.getItem(FOCUS))||['protein','fiber','steps']}catch{return['protein','fiber','steps']}}
async function refresh(){entries=(await getAll()).sort((a,b)=>a.date.localeCompare(b.date));renderAll()}
function recordsForPeriod(period){if(!entries.length)return[];const last=toDate(entries.at(-1).date);if(period==='today')return[entries.at(-1)];if(period==='week'){let start=new Date(last);start.setDate(last.getDate()-6);return entries.filter(e=>toDate(e.date)>=start)}if(period==='month'){return entries.filter(e=>{let d=toDate(e.date);return d.getFullYear()===last.getFullYear()&&d.getMonth()===last.getMonth()})}return entries}
function aggregate(list){const valid=(key)=>list.filter(e=>e[key]!=null);const sum=key=>list.reduce((s,e)=>s+Number(e[key]||0),0);const avg=key=>{let v=valid(key);return v.length?v.reduce((s,e)=>s+Number(e[key]),0)/v.length:null};return{days:list.length,intake:sum('intake'),tdee:sum('tdee'),balance:list.reduce((s,e)=>s+balance(e),0),weight:avg('weight'),protein:avg('protein'),fiber:avg('fiber'),steps:avg('steps'),water:avg('water'),sleep:avg('sleep')}}
function renderAll(){renderOverview();renderNutrition();renderTraining();renderProgress();renderSettings()}
function renderOverview(){const p=profile(), list=recordsForPeriod(currentPeriod), a=aggregate(list), latest=entries.at(-1);$('#profileName').textContent=p.name;$('#summaryBalance').textContent=signed(a.balance);$('#summaryDays').textContent=a.days+' erfasste Tage';$('#summaryIntake').textContent=kcal(a.intake);$('#summaryTdee').textContent=kcal(a.tdee);$('#summaryWeight').textContent=fmt(a.weight,' kg');let weights=list.filter(e=>e.weight!=null);$('#summaryWeightChange').textContent=weights.length>1?'Veränderung '+weightDelta(weights.at(-1).weight-weights[0].weight):'Kein Vergleich';renderFocus(latest,a);drawBarChart('overviewBalanceChart',entries.slice(-14),'balance');if(!latest){$('#latestDate').textContent='Noch keine Daten';$('#latestMetrics').innerHTML='';return}$('#latestDate').textContent=dateLong.format(toDate(latest.date));$('#latestMetrics').innerHTML=[['Aufnahme',kcal(latest.intake)],['TDEE',kcal(latest.tdee)],['Bilanz',signed(balance(latest))],['Gewicht',fmt(latest.weight,' kg')],['Protein',fmt(latest.protein,' g')],['Schritte',fmt(latest.steps,'',0)]].map(x=>`<div><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');$('#latestNote').textContent=latest.note||'Keine Notiz hinterlegt.'}
const focusDefs={protein:{icon:'💪',title:'Protein',value:(e)=>fmt(e?.protein,' g'),text:(e)=>e?.protein==null?'Nicht erfasst':`${n1.format(Math.max(0,TARGETS.protein-e.protein))} g bis 140 g`,pct:e=>Math.min(100,(e?.protein||0)/TARGETS.protein*100)},fiber:{icon:'🌾',title:'Ballaststoffe',value:e=>fmt(e?.fiber,' g'),text:e=>e?.fiber==null?'Nicht erfasst':`${n1.format(e.fiber)} von 30 g`,pct:e=>Math.min(100,(e?.fiber||0)/TARGETS.fiber*100)},steps:{icon:'🚶',title:'Schritte',value:e=>fmt(e?.steps,'',0),text:e=>e?.steps==null?'Nicht erfasst':`${n0.format(e.steps)} von 11.500`,pct:e=>Math.min(100,(e?.steps||0)/TARGETS.steps*100)},weight:{icon:'⚖️',title:'Gewicht',value:e=>fmt(e?.weight,' kg'),text:()=> 'Letzter Eintrag',pct:()=>75},water:{icon:'💧',title:'Wasser',value:e=>fmt(e?.water,' l'),text:e=>e?.water==null?'Noch nicht erfasst':`${n1.format(e.water)} von 2,5 l`,pct:e=>Math.min(100,(e?.water||0)/TARGETS.water*100)},sleep:{icon:'🌙',title:'Schlaf',value:e=>fmt(e?.sleep,' h'),text:e=>e?.sleep==null?'Noch nicht erfasst':`${n1.format(e.sleep)} von 8 h`,pct:e=>Math.min(100,(e?.sleep||0)/TARGETS.sleep*100)}};
function renderFocus(latest){let selected=focus().slice(0,3);$('#focusCards').innerHTML=selected.map(k=>{let d=focusDefs[k];return`<article class="focus-card"><span class="icon">${d.icon}</span><h3>${d.title}</h3><strong>${d.value(latest)}</strong><p>${d.text(latest)}</p><div class="meter"><i style="width:${d.pct(latest)}%"></i></div></article>`}).join('')}
function focusMarkup(){let selected=focus();return Object.entries(focusDefs).map(([k,d])=>`<label class="toggle"><span>${d.icon} ${d.title}</span><input type="checkbox" data-focus="${k}" ${selected.includes(k)?'checked':''}></label>`).join('')}
function bindFocus(container){container.innerHTML=focusMarkup();container.querySelectorAll('[data-focus]').forEach(input=>input.onchange=()=>{let selected=focus(),k=input.dataset.focus;if(input.checked&&!selected.includes(k)){if(selected.length>=3){input.checked=false;alert('Bitte maximal drei Werte auswählen.');return}selected.push(k)}else selected=selected.filter(x=>x!==k);localStorage.setItem(FOCUS,JSON.stringify(selected));renderAll()})}
function renderNutrition(){let list=$('#nutritionPeriod').value==='all'?entries:entries.slice(-Number($('#nutritionPeriod').value||entries.length)), q=$('#nutritionSearch').value.trim().toLowerCase();if(q)list=list.filter(e=>(e.date+' '+(e.note||'')).toLowerCase().includes(q));let a=aggregate(list);$('#nutritionProtein').textContent=fmt(a.protein,' g');$('#nutritionFiber').textContent=fmt(a.fiber,' g');$('#nutritionIntake').textContent=kcal(a.days?a.intake/a.days:null);$('#nutritionPeriodLabel').textContent=list.length+' Einträge';$('#nutritionRows').innerHTML=[...list].reverse().map(e=>`<tr><td>${dateShort.format(toDate(e.date))}</td><td>${kcal(e.intake)}</td><td>${kcal(e.tdee)}</td><td class="${balance(e)<=0?'negative':'positive'}">${signed(balance(e))}</td><td>${fmt(e.protein,' g')}</td><td>${fmt(e.fiber,' g')}</td><td><button data-edit-date="${e.date}">Bearbeiten</button></td></tr>`).join('')}
function renderTraining(){let list=entries.filter(e=>(e.training||0)>0||(e.trainingType||'').trim());$('#trainingCount').textContent=list.length;$('#trainingMinutes').textContent=n0.format(list.reduce((s,e)=>s+Number(e.training||0),0))+' min';$('#trainingSteps').textContent=fmt(aggregate(entries).steps,'',0);$('#trainingEmpty').hidden=!!list.length;$('#trainingList').innerHTML=[...list].reverse().map(e=>`<div class="training-item"><div><b>${dateShort.format(toDate(e.date))}</b><small>${e.training||0} Minuten</small></div><div><p>${e.trainingType||'Training'}</p><small>${e.note||'Keine Notiz'}</small></div><button data-edit-date="${e.date}">Bearbeiten</button></div>`).join('')}
function renderProgress(){drawLineChart('weightChart',entries.filter(e=>e.weight!=null),'weight');drawBarChart('balanceChart',entries,'balance');let weights=entries.filter(e=>e.weight!=null);$('#weightTrend').textContent=weights.length>1?`${dateShort.format(toDate(weights[0].date))} bis ${dateShort.format(toDate(weights.at(-1).date))}: ${weightDelta(weights.at(-1).weight-weights[0].weight)}`:'Nicht genügend Daten';$('#progressCount').textContent=entries.length+' Einträge';let groups=[];for(let i=0;i<entries.length;i+=7){let part=entries.slice(i,i+7),a=aggregate(part);groups.push({part,a})}$('#weekList').innerHTML=groups.reverse().map(g=>`<div class="week-item"><b>${dateShort.format(toDate(g.part[0].date))} – ${dateShort.format(toDate(g.part.at(-1).date))}</b><span>${g.part.length} Tage</span><strong class="${g.a.balance<=0?'negative':'positive'}">${signed(g.a.balance)}</strong></div>`).join('')}
function renderSettings(){let p=profile();$('#nameInput').value=p.name;bindFocus($('#focusSettings'));bindFocus($('#focusDialogSettings'));$('#dataInfo').textContent=`${entries.length} lokale Tagesdatensätze. Historische Daten: 1. Juni bis 2. Juli 2026; neue Einträge werden ergänzt.`}
function weightDelta(v){return(v>0?'+':v<0?'−':'')+n1.format(Math.abs(v))+' kg'}
function drawLineChart(id,list,key){let c=$('#'+id),ctx=c.getContext('2d'),w=Math.max(280,c.clientWidth),h=270,r=devicePixelRatio||1;c.width=w*r;c.height=h*r;ctx.setTransform(r,0,0,r,0,0);ctx.clearRect(0,0,w,h);if(list.length<2)return;let vals=list.map(e=>Number(e[key])),mi=Math.min(...vals),ma=Math.max(...vals);if(mi===ma){mi-=1;ma+=1}let p={l:42,r:13,t:18,b:28};ctx.strokeStyle='#dce5f3';ctx.fillStyle='#687595';ctx.font='11px system-ui';for(let i=0;i<5;i++){let y=p.t+(h-p.t-p.b)*i/4;ctx.beginPath();ctx.moveTo(p.l,y);ctx.lineTo(w-p.r,y);ctx.stroke();ctx.fillText(n1.format(ma-(ma-mi)*i/4),2,y+4)}ctx.beginPath();vals.forEach((v,i)=>{let x=p.l+(w-p.l-p.r)*i/(vals.length-1),y=p.t+(ma-v)/(ma-mi)*(h-p.t-p.b);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle='#0b42c8';ctx.lineWidth=3;ctx.stroke()}
function drawBarChart(id,list){let c=$('#'+id),ctx=c.getContext('2d'),w=Math.max(280,c.clientWidth),h=270,r=devicePixelRatio||1;c.width=w*r;c.height=h*r;ctx.setTransform(r,0,0,r,0,0);ctx.clearRect(0,0,w,h);if(!list.length)return;let vals=list.map(balance),max=Math.max(1,...vals.map(Math.abs)),p={l:10,r:10,t:15,b:20},mid=(h-p.t-p.b)/2+p.t;ctx.strokeStyle='#bfcadd';ctx.beginPath();ctx.moveTo(p.l,mid);ctx.lineTo(w-p.r,mid);ctx.stroke();let gap=3,bw=Math.max(3,(w-p.l-p.r-gap*(vals.length-1))/vals.length);vals.forEach((v,i)=>{let x=p.l+i*(bw+gap),bh=Math.abs(v)/max*(h-p.t-p.b)/2;ctx.fillStyle=v<=0?'#168a54':'#d94747';ctx.fillRect(x,v<=0?mid-bh:mid,bw,bh)})}
function setScreen(name){$$('.screen').forEach(s=>s.classList.toggle('active',s.dataset.screen===name));$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.target===name));window.scrollTo({top:0,behavior:'smooth'});setTimeout(()=>{if(name==='overview'||name==='progress')renderAll()},50)}
function resetForm(){editingDate=null;$('#entryForm').reset();$('#dateInput').value=todayIso();$('#entryTitle').textContent='Tag erfassen';$('#deleteEntry').hidden=true;$('#entryStatus').textContent='';liveBalance()}
async function openEntry(date){resetForm();if(date){let e=await getOne(date);if(e){editingDate=e.date;['date','weight','intake','tdee','protein','fiber','steps','water','sleep','training','trainingType','note'].forEach(k=>$('#'+k+'Input').value=e[k]??'');$('#entryTitle').textContent='Eintrag bearbeiten';$('#deleteEntry').hidden=false;liveBalance()}}$('#entryDialog').showModal()}
function liveBalance(){let i=optional($('#intakeInput').value),t=optional($('#tdeeInput').value);$('#liveBalance').textContent=i==null||t==null?'–':signed(i-t)}
function formEntry(){let g=k=>optional($('#'+k+'Input').value);return{date:$('#dateInput').value,weight:g('weight'),intake:g('intake'),tdee:g('tdee'),protein:g('protein'),fiber:g('fiber'),steps:g('steps'),water:g('water'),sleep:g('sleep'),training:g('training'),trainingType:$('#trainingTypeInput').value.trim(),note:$('#noteInput').value.trim(),source:'Lokale Eingabe',updatedAt:new Date().toISOString()}}
function confirm(title,text,fn){pendingAction=fn;$('#confirmTitle').textContent=title;$('#confirmText').textContent=text;$('#confirmDialog').showModal()}
function download(name,text,type){let url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
function exportJson(){download('fittrack-backup-'+todayIso()+'.json',JSON.stringify({app:'FitTrack Test-App',version:2,profile:profile(),focus:focus(),entries},null,2),'application/json')}
function exportCsv(){let cols=['date','tdee','intake','balance','weight','protein','fiber','steps','water','sleep','training','trainingType','note'],esc=v=>'"'+String(v??'').replaceAll('"','""')+'"';download('fittrack-daten-'+todayIso()+'.csv','\ufeff'+[cols.join(';'),...entries.map(e=>cols.map(k=>esc(k==='balance'?balance(e):e[k])).join(';'))].join('\n'),'text/csv')}
async function importJson(){let f=$('#importFile').files[0];if(!f)return $('#importStatus').textContent='Bitte Datei auswählen.';try{let p=JSON.parse(await f.text()),list=Array.isArray(p)?p:p.entries;if(!Array.isArray(list))throw Error('Keine Einträge gefunden');for(const e of list){if(e.date&&Number.isFinite(Number(e.intake))&&Number.isFinite(Number(e.tdee)))await put({...e,date:String(e.date).slice(0,10),intake:Number(e.intake),tdee:Number(e.tdee)})}if(p.profile?.name)localStorage.setItem(PROFILE,JSON.stringify({name:p.profile.name}));if(Array.isArray(p.focus))localStorage.setItem(FOCUS,JSON.stringify(p.focus.slice(0,3)));await refresh();$('#importStatus').textContent=list.length+' Einträge importiert.'}catch(err){$('#importStatus').textContent='Import fehlgeschlagen: '+err.message}}
function status(){let on=navigator.onLine;$('#connectionStatus').textContent=on?'Online · offline bereit':'Offline';$('#connectionStatus').classList.toggle('offline',!on)}
function bind(){$$('.bottom-nav button').forEach(b=>b.onclick=()=>setScreen(b.dataset.target));$$('.open-entry').forEach(b=>b.onclick=()=>openEntry());$('#openEntryTop').onclick=()=>openEntry();$('#editLatest').onclick=()=>entries.at(-1)&&openEntry(entries.at(-1).date);$('#editFocus').onclick=()=>$('#focusDialog').showModal();$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());$('#periodSwitch').onclick=e=>{let b=e.target.closest('[data-period]');if(!b)return;currentPeriod=b.dataset.period;$('#periodSwitch').querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));renderOverview()};$('#nutritionPeriod').onchange=renderNutrition;$('#nutritionSearch').oninput=renderNutrition;document.body.onclick=e=>{let b=e.target.closest('[data-edit-date]');if(b)openEntry(b.dataset.editDate)};$('#intakeInput').oninput=$('#tdeeInput').oninput=liveBalance;$('#entryForm').onsubmit=async e=>{e.preventDefault();let v=formEntry();if(!v.date||v.intake==null||v.tdee==null){$('#entryStatus').textContent='Datum, Aufnahme und TDEE fehlen.';return}await put(v);await refresh();$('#entryStatus').textContent='Lokal gespeichert.';setTimeout(()=>$('#entryDialog').close(),350)};$('#deleteEntry').onclick=()=>editingDate&&confirm('Eintrag löschen?',dateShort.format(toDate(editingDate)),async()=>{await remove(editingDate);$('#entryDialog').close();await refresh()});$('#confirmDialog').onclose=async()=>{if($('#confirmDialog').returnValue==='confirm'&&pendingAction)await pendingAction();pendingAction=null};$('#saveName').onclick=()=>{localStorage.setItem(PROFILE,JSON.stringify({name:$('#nameInput').value.trim()||'Jenny'}));renderAll();$('#nameStatus').textContent='Name gespeichert.'};$('#exportJson').onclick=exportJson;$('#exportCsv').onclick=exportCsv;$('#importJson').onclick=importJson;$('#clearData').onclick=()=>confirm('Alle lokalen Daten löschen?','Alle Einträge dieses Browsers werden gelöscht. Ein Backup kann sie wiederherstellen.',async()=>{await clear();localStorage.setItem(SEED,'1');await refresh()});window.addEventListener('online',status);window.addEventListener('offline',status);window.addEventListener('resize',()=>{if($('.screen.active')?.dataset.screen==='overview'||$('.screen.active')?.dataset.screen==='progress')renderAll()});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installButton').hidden=false});$('#installButton').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installButton').hidden=true}}
async function init(){bind();db=await openDb();await seedMissing();await refresh();status();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=2',{scope:'./'}).catch(console.error)}
init().catch(err=>{console.error(err);alert('FitTrack konnte die lokale Datenbank nicht öffnen.')});
})();