if(typeof document==='undefined'){
 const C='fittrack-local-v3',A=['./','./index.html','./styles.css','./script.js'];
 addEventListener('install',e=>e.waitUntil(caches.open(C).then(c=>c.addAll(A)).then(()=>skipWaiting())));
 addEventListener('activate',e=>e.waitUntil(caches.keys().then(k=>Promise.all(k.filter(x=>x!==C).map(x=>caches.delete(x)))).then(()=>clients.claim())));
 addEventListener('fetch',e=>{if(e.request.method==='GET')e.respondWith(caches.match(e.request).then(r=>r||fetch(e.request).catch(()=>caches.match('./index.html'))))});
}else{(()=>{'use strict';
const SEED=[['2026-06-26',2007,1824,76.9,128,33.9,4221],['2026-06-27',2327,1668,76.9,110,35.8,4422],['2026-06-28',2305,3048,76.9,148,7.6,4936],['2026-06-29',2240,2470,76.9,152,28.3,5941],['2026-06-30',2656,1628,76.9,102,27.7,12508],['2026-07-01',2325,1769,76.4,146,36.3,11511],['2026-07-02',2591,1728,76.1,137.6,36.9,11819]].map(x=>({date:x[0],tdee:x[1],intake:x[2],weight:x[3],protein:x[4],fiber:x[5],steps:x[6]}));
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],N=new Intl.NumberFormat('de-DE',{maximumFractionDigits:1}),I=new Intl.NumberFormat('de-DE',{maximumFractionDigits:0}),D=new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit',year:'numeric'}),DB='fittrack-local',S='entries';let db,rows=[],action=null;
const day=s=>new Date(s+'T12:00:00'),balance=e=>+e.intake-+e.tdee,num=v=>v===''?null:+v,fmt=(v,u='')=>v==null?'–':N.format(v)+u,signed=v=>(v>0?'+':v<0?'−':'')+I.format(Math.abs(v))+' kcal',today=()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);
function open(){return new Promise((ok,no)=>{let r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.objectStoreNames.contains(S)||r.result.createObjectStore(S,{keyPath:'date'});r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}function store(m='readonly'){return db.transaction(S,m).objectStore(S)}function getAll(){return new Promise((ok,no)=>{let r=store().getAll();r.onsuccess=()=>ok(r.result||[]);r.onerror=()=>no(r.error)})}function put(e){return new Promise((ok,no)=>{let r=store('readwrite').put(e);r.onsuccess=ok;r.onerror=()=>no(r.error)})}function remove(k){return new Promise((ok,no)=>{let r=store('readwrite').delete(k);r.onsuccess=ok;r.onerror=()=>no(r.error)})}function clear(){return new Promise((ok,no)=>{let r=store('readwrite').clear();r.onsuccess=ok;r.onerror=()=>no(r.error)})}
async function refresh(){rows=(await getAll()).sort((a,b)=>a.date.localeCompare(b.date));render()}
function render(){let last=rows.at(-1),name=localStorage.ftName||'Jenny';$('#displayName').textContent=name;$('#nameInput').value=name;$('#recordCount').textContent=rows.length;if(!last){['latestBalance','latestWeight','weekBalance','latestIntake','latestTdee','latestBalanceDetail','latestProtein','latestFiber','latestSteps'].forEach(x=>$('#'+x).textContent='–');$('#latestBalanceDate').textContent='Noch kein Eintrag';$('#latestDateHeading').textContent='Noch keine Daten';history();bars([]);return}let b=balance(last),week=rows.slice(-7);$('#latestBalance').textContent=signed(b);$('#latestBalanceDate').textContent=D.format(day(last.date));$('#latestWeight').textContent=fmt(last.weight,' kg');$('#latestDateHeading').textContent=D.format(day(last.date));$('#latestIntake').textContent=I.format(last.intake)+' kcal';$('#latestTdee').textContent=I.format(last.tdee)+' kcal';$('#latestBalanceDetail').textContent=signed(b);$('#latestProtein').textContent=fmt(last.protein,' g');$('#latestFiber').textContent=fmt(last.fiber,' g');$('#latestSteps').textContent=last.steps==null?'–':I.format(last.steps);$('#proteinMeter').style.width=Math.min(100,(last.protein||0)/140*100)+'%';$('#fiberMeter').style.width=Math.min(100,(last.fiber||0)/30*100)+'%';$('#stepsMeter').style.width=Math.min(100,(last.steps||0)/11500*100)+'%';$('#weekBalance').textContent=signed(week.reduce((s,e)=>s+balance(e),0));$('#weekDays').textContent=week.length+' erfasste Tage';let prev=rows.filter(e=>e.weight!=null).at(-2);$('#weightChange').textContent=prev?signedWeight(last.weight-prev.weight):'Kein Vergleich möglich';$('#editLatestButton').hidden=false;bars(week);chart(rows.filter(e=>e.weight!=null).slice(-14));history()}
function signedWeight(v){return(v>0?'+':v<0?'−':'')+N.format(Math.abs(v))+' kg'}function bars(a){let m=Math.max(1,...a.map(e=>Math.abs(balance(e))));$('#dayBars').innerHTML=a.map(e=>{let v=balance(e),h=Math.max(5,Math.abs(v)/m*46);return`<div class="day-bar"><small>${e.date.slice(8)}</small><i class="${v<=0?'deficit':'surplus'}" style="height:${h}%"></i><b>${v>0?'+':v<0?'−':''}${I.format(Math.abs(v))}</b></div>`}).join('')}
function chart(a){let c=$('#weightChart'),x=c.getContext('2d'),w=c.clientWidth||400,h=255,r=devicePixelRatio||1;c.width=w*r;c.height=h*r;x.setTransform(r,0,0,r,0,0);x.clearRect(0,0,w,h);if(a.length<2)return $('#weightChartNote').textContent='Noch nicht genügend Gewichtsdaten.';let v=a.map(e=>+e.weight),mi=Math.min(...v)-.2,ma=Math.max(...v)+.2;x.beginPath();v.forEach((n,i)=>{let px=30+(w-45)*i/(v.length-1),py=15+(ma-n)/(ma-mi)*(h-40);i?x.lineTo(px,py):x.moveTo(px,py)});x.strokeStyle='#0b42c8';x.lineWidth=3;x.stroke();$('#weightChartNote').textContent=v.length+' Werte · '+signedWeight(v.at(-1)-v[0])}
function history(){let q=$('#historySearch').value.toLowerCase(),n=$('#historyPeriod').value,a=[...rows].reverse();if(n!=='all')a=a.slice(0,+n);if(q)a=a.filter(e=>(e.date+' '+(e.note||'')).toLowerCase().includes(q));$('#historyEmpty').hidden=!!a.length;$('#historyRows').innerHTML=a.map(e=>`<tr><td>${D.format(day(e.date))}</td><td>${I.format(e.intake)}</td><td>${I.format(e.tdee)}</td><td class="${balance(e)<=0?'negative':'positive'}">${signed(balance(e)).replace(' kcal','')}</td><td>${fmt(e.weight,' kg')}</td><td>${fmt(e.protein,' g')}</td><td>${e.steps==null?'–':I.format(e.steps)}</td><td class="actions"><button data-edit="${e.date}">Bearbeiten</button><button class="danger" data-delete="${e.date}">Löschen</button></td></tr>`).join('')}
function screen(s){$$('.screen').forEach(x=>x.classList.toggle('active',x.dataset.screen===s));$$('.bottom-nav button').forEach(x=>x.classList.toggle('active',x.dataset.target===s));scrollTo(0,0)}function reset(){$('#entryForm').reset();$('#dateInput').value=today();$('#formTitle').textContent='Tagesdaten eintragen';$('#saveStatus').textContent='';live()}function fill(e){['date','weight','intake','tdee','protein','fiber','steps','water','sleep','training','note'].forEach(k=>$('#'+k+'Input').value=e[k]??'');screen('entry');live()}function live(){let i=num($('#intakeInput').value),t=num($('#tdeeInput').value);$('#liveBalance').textContent=i==null||t==null?'–':signed(i-t)}function form(){let g=x=>num($('#'+x+'Input').value);return{date:$('#dateInput').value,weight:g('weight'),intake:g('intake'),tdee:g('tdee'),protein:g('protein'),fiber:g('fiber'),steps:g('steps'),water:g('water'),sleep:g('sleep'),training:g('training'),note:$('#noteInput').value.trim()}}
function download(name,text,type){let a=document.createElement('a'),u=URL.createObjectURL(new Blob([text],{type}));a.href=u;a.download=name;a.click();URL.revokeObjectURL(u)}function backup(){download('fittrack-backup.json',JSON.stringify({name:localStorage.ftName||'Jenny',entries:rows},null,2),'application/json')}function csv(){let h='date;tdee;intake;balance;weight;protein;fiber;steps;water;sleep;training;note\n',a=rows.map(e=>[e.date,e.tdee,e.intake,balance(e),e.weight,e.protein,e.fiber,e.steps,e.water,e.sleep,e.training,(e.note||'').replaceAll(';',',')].join(';')).join('\n');download('fittrack-daten.csv','\ufeff'+h+a,'text/csv')}
$$('.bottom-nav button').forEach(b=>b.onclick=()=>screen(b.dataset.target));$('#quickAddButton').onclick=()=>{reset();screen('entry')};$('#resetFormButton').onclick=reset;$('#intakeInput').oninput=$('#tdeeInput').oninput=live;$('#editLatestButton').onclick=()=>rows.at(-1)&&fill(rows.at(-1));$('#entryForm').onsubmit=async e=>{e.preventDefault();let v=form();if(!v.date||v.intake==null||v.tdee==null)return;await put(v);await refresh();$('#saveStatus').textContent='Lokal gespeichert.'};$('#historySearch').oninput=history;$('#historyPeriod').onchange=history;$('#historyRows').onclick=e=>{let a=e.target.dataset.edit,d=e.target.dataset.delete;if(a)fill(rows.find(x=>x.date===a));if(d){action=async()=>{await remove(d);await refresh()};$('#confirmTitle').textContent='Eintrag löschen?';$('#confirmText').textContent=D.format(day(d));$('#confirmDialog').showModal()}};$('#confirmDialog').onclose=async()=>{if($('#confirmDialog').returnValue==='confirm'&&action)await action();action=null};$('#exportJsonButton').onclick=backup;$('#exportCsvButton').onclick=csv;$('#importButton').onclick=async()=>{let f=$('#importFileInput').files[0];if(!f)return;try{let p=JSON.parse(await f.text()),a=p.entries||p;for(let e of a)await put(e);if(p.name)localStorage.ftName=p.name;await refresh();$('#importStatus').textContent='Importiert.'}catch{$('#importStatus').textContent='Import fehlgeschlagen.'}};$('#saveNameButton').onclick=()=>{localStorage.ftName=$('#nameInput').value||'Jenny';render();$('#nameStatus').textContent='Gespeichert.'};$('#clearDataButton').onclick=()=>{action=async()=>{await clear();localStorage.seeded='1';await refresh()};$('#confirmTitle').textContent='Alle Daten löschen?';$('#confirmText').textContent='Diese Aktion kann nicht rückgängig gemacht werden.';$('#confirmDialog').showModal()};function status(){let o=navigator.onLine;$('#connectionStatus').textContent=o?'Online · offline bereit':'Offline';$('#connectionStatus').classList.toggle('offline',!o)}addEventListener('online',status);addEventListener('offline',status);addEventListener('resize',render);
(async()=>{db=await open();if(!localStorage.seeded){for(let e of SEED)await put(e);localStorage.seeded='1'}reset();await refresh();status();navigator.serviceWorker?.register('./script.js?sw=1')})().catch(console.error)
})();}
